# See: https://golangci-lint.run/docs/configuration/file/
version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
  settings:
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - os.Setenv
        - os.Unsetenv

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - satt/go-template

run:
  timeout: 5m
  modules-download-mode: readonly
  tests: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
