version: "3"

includes:
  mise: tasks/MiseTasks.yml
  yml: tasks/YamlTasks.yml
  json: tasks/JsonTasks.yml
  md: tasks/MarkdownTasks.yml
  gh: tasks/GitHubTasks.yml
  go: tasks/GoTasks.yml

tasks:
  default:
    cmds:
      - task: list
      - task: mise:versions

  list:
    desc: List all tasks
    cmd: task --list-all
    aliases:
      - l

  setup:
    desc: "Setup project"
    cmds:
      - task: mise:setup
      - task: yml:setup
    aliases:
      - s

  update:
    desc: "Update project dependencies"
    cmds:
      - task: mise:update
    aliases:
      - u

  check:
    desc: "Check"
    deps:
      - yml:check
      - json:check
      - md:check
      - gh:check
      - go:check
    aliases:
      - c

  fix-and-check:
    desc: "Fix and check"
    deps:
      - yml:check
      - json:fix-and-check
      - md:fix-and-check
      - gh:check
      - go:fix-and-check
    aliases:
      - fc

  tag:*:
    desc: "Create a new tag"
    vars:
      VERSION: "{{index .MATCH 0}}"
    cmds:
      - git tag -a -m "Release v{{.VERSION}}" v{{.VERSION}}
      - git push --follow-tags
