version: "3"

includes:
  mise: tasks/MiseTasks.yml
  yml: tasks/YamlTasks.yml
  json: tasks/JsonTasks.yml
  md: tasks/MarkdownTasks.yml
  gh: tasks/GitHubTasks.yml
  go: tasks/GoTasks.yml

tasks:
  default:
    cmds:
      - task: list
      - task: mise:versions

  list:
    desc: List all tasks
    cmd: task --list-all
    aliases:
      - l

  select-run:
    desc: "Select and run with fzf"
    cmds:
      - ./tasks/task-select-run.sh
    aliases:
      - sr

  setup:
    desc: "Setup project"
    cmds:
      - task: mise:setup
    aliases:
      - s

  check:
    desc: "Check"
    deps:
      - yml:check
      - json:check
      - md:check
      - gh:check
      - go:check
    aliases:
      - c

  tag:*:
    desc: "Create a new tag"
    vars:
      VERSION: "{{index .MATCH 0}}"
    cmds:
      - git tag -a -m "Release v{{.VERSION}}" v{{.VERSION}}
      - git push --follow-tags
