version: "3"

tasks:
  install:
    desc: "Install Go dependencies"
    cmd: go mod tidy

  run:
    desc: "Run Go"
    cmds:
      - go run ./main.go

  build:
    desc: "Build Go binary"
    cmds:
      - go build .

  fix-and-check:
    desc: "Fix and check Go code"
    cmds:
      - task: fix
      - task: check
  aliases:
    - fc

  fix:
    desc: "Fix Go code"
    cmds:
      - task: fmt
      - task: lint:fix

  check:
    desc: "Check Go code"
    cmds:
      - task: lint
      - task: test
      - task: build

  lint:
    desc: "Lint Go code"
    cmd: golangci-lint run

  lint:fix:
    desc: "Lint Go code and auto fix"
    cmd: golangci-lint run --fix

  fmt:
    desc: "Format Go code"
    cmd: golangci-lint fmt

  test:unit:
    desc: "Run Go tests"
    cmd: go test ./internal/...
    aliases:
      - test

  test:integration:
    desc: "Run integration tests"
    cmd: go test ./tests/...
